version: "3"
services:

  mysql:
    container_name: "mysql"
    hostname: "mysql"
    image: yobasystems/alpine-mariadb:latest
    restart: "always"
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./cmd/sql/bludgeon_mysql.sql:/docker-entrypoint-initdb.d/bludgeon.sql

  example:
    container_name: example
    hostname: example
    image: ghcr.io/antonio-alexander/go-blog-data-consistency:latest
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./cmd/Dockerfile
      args:
        - PLATFORM=linux/amd64
        - GO_ARCH=amd64
        # - GO_ARCH=arm
        # - GO_ARM=7
    environment:
      HOSTNAME: "mysql"
      PORT: "3306"
      USERNAME: "root"
      PASSWORD: "mysql"
      DATABASE: "bludgeon"
